var game = {
    water: true,
    gravOn: true,
    gravAmount: 9.8,
    moveSpeed: 4,
    charName: "Deciem",
    enemies: true,
    charHealth: 10,
    damage: 1,
    backgroundImage: "sky",
    levelName: "Field Zone",
    worldNumber: 1,
    levelNumber: 1,
    runSpeed: 8,
    allowRunning: false,
    multipleEnemyTypes: false,
    enemyHealth: 2,
    enemyDamage: 1,
    allowLevelDeath: true,
    allowHealthRestore: true,
    healthRestore: 1,
    entryMessage: "Welcome hero! Press right!",
    deathMessage: "You have died.",
    savePoints: true,
    savePointMessage: "Stay a while and rest your weary soul.",
    swimSpeed: 2,
    breathCounter: 100,
    displayBreathCounter: false,
    breathDecay: 1,
    levelTimer: 300,
    mapMoveSpeed: 1,
    backpackAllowed: false,
    backpackMaxWeight: 300,
    swordWeight: 5,
    armorWeight: 30,
    monsterMaterialWeight: 4,
    fallDamage: true,
    burdenedMoveSpeed: 2,
    burdenedSwimSpeed: 0,
    allowEnemyMovement: false,
    victoryMessage: "There is no end goal, no princess, no castles. No fairies will help you on your journey. Continue on hero.",
    enemyName: "Toddlerkin",
    lightLevel: "night"
};

